# Site Settings
title: Base9
description: >
  An educational virtual machine
baseurl: /b9
github_username: b9org
theme: minima
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
highlighter: rouge
